services:
  db:
    image: postgres:14-alpine
    container_name: lab4-postgres-zad3
    environment:
      POSTGRES_USER: lab4user
      POSTGRES_PASSWORD: lab4password
      POSTGRES_DB: lab4db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

  app:
    image: alpine:3.20
    container_name: lab4-app-zad3
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_USER: lab4user
      DATABASE_PASSWORD: lab4password
      DATABASE_NAME: lab4db
    command: ["sh", "-c", "echo 'Łączenie z bazą danych pod adresem db:5432...' && sleep 300"]
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  backend-net:
    driver: bridge